blog/urls.py
from django.urls import path

from blog import views


urlpatterns = [
    path("", views.get_post_list, name="post_list"),
    path("list", views.PostListView.as_view(), name="post_list2"),
    path("add/", views.add_new_post, name="post_add"),
    path("new", views.PostCreateView.as_view(), name="post_new"),
    path("<int:pk>", views.get_post_detail, name="post_detail"),
    path("<int:pk>/details", views.PostDetailView.as_view(), name="post_detail2"),
    path("<int:pk>/edit", views.PostUpdateView.as_view(), name="post_edit"),
    path("<int:pk>/delete", views.PostDeleteView.as_view(), name="post_delete"),
    path("about", views.about_us, name="about_us"),
    path("about2", views.AboutView.as_view(), name="about_us2"),
]

makina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("vehicles.urls")),
    path("posts/", include("blog.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

vehicles/urls.py
from django.urls import path, include
from rest_framework import routers

from vehicles.views import (
    add_vehicle,
    get_vehicles,
    get_vehicle_details,
    put_vehicle_on_sale,
    show_secret_page,
)
from vehicles.viewsets import VehicleViewSet


router = routers.DefaultRouter()
router.register('vehicles', VehicleViewSet)


urlpatterns = [
    path("", get_vehicles, name="vehicle_list"),
    path("api/", include(router.urls)),
    path("super-secret/", show_secret_page, name="secret_page"),
    path("add/", add_vehicle, name="vehicle_add"),
    path("<int:pk>/", get_vehicle_details, name="vehicle_detail"),
    path("<int:pk>/put-on-sale/", put_vehicle_on_sale, name="vehicle_sale"),
]

vehicles/models.py
from django.db import models
from django.contrib.auth.models import User


class Merchant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=False, blank=False)
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name


# CREATE TABLE vehicles ()
class Vehicle(models.Model):
    AUTOMATIC = "automatic"
    MANUAL = "manual"
    TRANSMISSION_CHOICES = [
        (AUTOMATIC, "Automatic"),
        (MANUAL, "Manual"),
    ]

    # brand varchar(100) not null
    brand = models.CharField(max_length=100, null=False)
    # brand varchar(100) not null
    model = models.CharField(max_length=100, null=False)
    # year int not null constraint chk_positive check (year > 0)
    year = models.PositiveIntegerField(null=False)
    transmission = models.CharField(max_length=32, null=True,
                                    choices=TRANSMISSION_CHOICES)
    description = models.TextField(null=True, blank=True)
    merchant = models.ForeignKey(Merchant,
                                 null=True, blank=False,
                                 on_delete=models.CASCADE, related_name="vehicles")
    is_on_sale = models.BooleanField(default=False)

    class Meta:
        permissions = (
            ('can_put_on_sale', 'Put vehicle on sale'),
        )

    def __str__(self):
        return f'{self.brand} {self.model}'


class Photo(models.Model):
    photo = models.ImageField(null=True, upload_to="photos")
    vehicle = models.ForeignKey(Vehicle, null=False, blank=False,
                                related_name='photos', on_delete=models.CASCADE)

    def __str__(self):
        return self.photo.name


class Comment(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    comment = models.TextField(null=False, blank=False)
    vehicle = models.ForeignKey(Vehicle, null=False, blank=False,
                                related_name="comments", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

vehicles/forms.py
from django import forms

from vehicles.models import Vehicle


class VehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = [
            'brand',
            'model',
            'year',
            'transmission',
            'description',
        ]

vehicles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test

from vehicles.models import Vehicle
from vehicles.forms import VehicleForm


# 127.0.0.1:8000/vehicles
def get_vehicles(request):
    # select * from vehicles_vehicle
    vehicles = Vehicle.objects.all()
    return render(request, "vehicles/vehicle_list.html", context={
        "vehicles": vehicles
    })


# 127.0.0.1:8000/vehicles/2
def get_vehicle_details(request, pk):
    # select * from vehicles_vehicle where id = %s
    vehicle = Vehicle.objects.get(pk=pk)
    return render(request, "vehicles/vehicle_detail.html", context={
        "vehicle": vehicle
    })

@login_required
@permission_required('vehicles.can_put_on_sale', raise_exception=True)
def put_vehicle_on_sale(request, pk):
    if request.method == 'POST':
        vehicle = Vehicle.objects.get(pk=pk)
        vehicle.is_on_sale = True
        vehicle.save()
        return redirect('vehicle_detail', pk=pk)


@login_required
def add_vehicle(request):
    if request.method == 'POST':
        form = VehicleForm(request.POST)
        if form.is_valid():
            vehicle = form.save()
            return redirect('vehicle_detail', pk=vehicle.pk)
    else:
        form = VehicleForm()
    return render(request, "vehicles/vehicle_form.html", context={
        'form': form
    })


def is_sdacademy_dev(user):
    return user.email.endswith('@sdacademy.dev')


@user_passes_test(is_sdacademy_dev)
def show_secret_page(request):
    return render(request, 'vehicles/secret.html')

vehicles/templates/secret.html
{% extends "base.html" %}

{% block content %}
<div role="alert" class="alert alert-danger">
    This is very secret!
</div>
{% endblock content %}

vehicles/templates/vehicle_detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ vehicle.brand }} {{ vehicle.model }} ({{ vehicle.year }})</h1>
{% if vehicle.is_on_sale %}
<div class="alert alert-warning" role="alert">
    This vehicle is on sale!
</div>
{% endif %}
<p>Transmission: {{ vehicle.transmission }}</p>
<p>
    <a href="{% url 'vehicle_list' %}">Go back to listing</a>
</p>
<p>
    <form action="{% url 'vehicle_sale' pk=vehicle.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-info">Put on Sale</button>
    </form>
</p>
{% endblock content %}

vehicles/templates/vehicle_form.html
{% extends "base.html" %}

{% block content %}
<h1>Add new Vehicle</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-dark">Save</button>
</form>
{% endblock content %}

vehicles/templates/vehicle_list.html
{% extends "base.html" %}

{% block content %}
    <div class="d-flex justify-content-between my-2">
        <h1>Vehicles for Sale</h1>
        <a href="{% url 'vehicle_add' %}" class="btn btn-secondary align-self-end">Add new Vehicle</a>
    </div>
    <table class="table">
        <caption>Latest Vehicles</caption>
        <thead>
            <tr>
                <th>Brand</th>
                <th>Model</th>
                <th>Year</th>
                <th>Transmission</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for vehicle in vehicles %}
            <tr>
                <td>{{ vehicle.brand }}</td>
                <td>{{ vehicle.model }}</td>
                <td>{{ vehicle.year }}</td>
                <td>{{ vehicle.get_transmission_display }}</td>
                <td>
                    <!-- <a href="/vehicles/{{ vehicle.id }}">View Details</a> -->
                    <a href="{% url 'vehicle_detail' pk=vehicle.id %}">View Details</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr />
    <a href="{% url 'secret_page' %}">SECRET PAGE</a>
    <hr />
    <pre id="debug-display"></pre>
{% endblock content %}

{% block scripts %}
{{ block.super }}
<script>
var url = '/vehicles/api/vehicles/';

var debugDisplay = document.getElementById("debug-display");

window.onload = function (e) {
    fetch(url, {
        headers: {
            'Accept': 'application/json'
        }
    })
    .then(resp => resp.json())
    .catch(err => console.log(err))
    .then(data => {
        debugDisplay.innerText = JSON.stringify(data, null, 2);
    });
}
</script>
{% endblock scripts %}