blog/urls.py
from django.urls import path

from blog import views


urlpatterns = [
    path("", views.get_post_list, name="post_list"),
    path("list", views.PostListView.as_view(), name="post_list2"),
    path("add/", views.add_new_post, name="post_add"),
    path("new", views.PostCreateView.as_view(), name="post_new"),
    path("<int:pk>", views.get_post_detail, name="post_detail"),
    path("<int:pk>/details", views.PostDetailView.as_view(), name="post_detail2"),
    path("<int:pk>/edit", views.PostUpdateView.as_view(), name="post_edit"),
    path("<int:pk>/delete", views.PostDeleteView.as_view(), name="post_delete"),
    path("about", views.about_us, name="about_us"),
    path("about2", views.AboutView.as_view(), name="about_us2"),
]

core/urls.py
from django.urls import path

from core.views import HomeView, save_preferences


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("save-preferences", save_preferences, name="save_preferences")
]

makina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("vehicles.urls")),
    path("posts/", include("blog.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

core/models.py
from django.db import models

# Create your models here.

vehicles/models.py
from django.db import models
from django.contrib.auth.models import User


class Merchant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=False, blank=False)
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name


# CREATE TABLE vehicles ()
class Vehicle(models.Model):
    AUTOMATIC = "automatic"
    MANUAL = "manual"
    TRANSMISSION_CHOICES = [
        (AUTOMATIC, "Automatic"),
        (MANUAL, "Manual"),
    ]

    # brand varchar(100) not null
    brand = models.CharField(max_length=100, null=False)
    # brand varchar(100) not null
    model = models.CharField(max_length=100, null=False)
    # year int not null constraint chk_positive check (year > 0)
    year = models.PositiveIntegerField(null=False)
    transmission = models.CharField(max_length=32, null=True,
                                    choices=TRANSMISSION_CHOICES)
    description = models.TextField(null=True, blank=True)
    merchant = models.ForeignKey(Merchant,
                                 null=True, blank=False,
                                 on_delete=models.CASCADE, related_name="vehicles")
    is_on_sale = models.BooleanField(default=False)

    class Meta:
        permissions = (
            ('can_put_on_sale', 'Put vehicle on sale'),
        )

    def __str__(self):
        return f'{self.brand} {self.model}'


class Photo(models.Model):
    photo = models.ImageField(null=True, upload_to="photos")
    vehicle = models.ForeignKey(Vehicle, null=False, blank=False,
                                related_name='photos', on_delete=models.CASCADE)

    def __str__(self):
        return self.photo.name


class Comment(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    comment = models.TextField(null=False, blank=False)
    vehicle = models.ForeignKey(Vehicle, null=False, blank=False,
                                related_name="comments", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

core/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "home.html"


def save_preferences(request):
    print("SAVE PREFERENCES::request.POST =", request.POST)

    theme = request.POST.get("theme", "light")

    request.session['theme'] = theme

    return redirect("/")

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Makina</title>
    {% block styles %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% endblock styles %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-{{ request.session.theme|default:"light"}} bg-{{ request.session.theme|default:"light"}}">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">makina.al</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'vehicle_list' %}">Automjete</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Tregtare</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'post_list' %}">Lajme</a>
              </li>
            </ul>
            {% if user.is_authenticated %}
            <ul class="navbar-nav mb-2 mb-lg-0">
              <li>
                <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
              </li>
            </ul>
            {% else %}
            <ul class="navbar-nav mb-2 mb-lg-0">
              <li>
                <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
              </li>
            </ul>
            {% endif %}
          </div>
        </div>
      </nav>
    <main class="container-fluid">{% block content %}{% endblock content %}</main>
    <footer>
        <p>Copyright &copy; 2021 - SDA PythonTirana2</p>
    </footer>
    {% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% endblock scripts %}
</body>
</html>

core/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome to makina.al</h1>
<p>THEME = <code>{{ request.session.theme }}</code></p>
<form action="{% url 'save_preferences' %}" method="POST">
    {% csrf_token %}
    <p>Choose your theme?</p>
    <ul>
        <li>
            <label>
                <input type="radio" name="theme" value="light">
                Light
            </label>
        </li>
        <li>
            <label>
                <input type="radio" name="theme" value="dark">
                Dark
            </label>
        </li>
    </ul>
    <button type="submit" class="btn btn-secondary">Save Preferences</button>
</form>
{% endblock content %}